name: Carlo
favicon: null
layout_spectrum: 0.9962678491137922
typography_spectrum: 0.9193660782184452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6937191064935178
  lightness: 0.4251544976141304
  saturation: 0.7836060088593513
  rhythmicContrast: 0.8386641086544842
purpose: []
